### ISSUE TITLE
2 byte code compilation warnings: org-format-latex, org-translate-time and org-publish-resolve-external-fuzzy-link

### ISSUE THREAD

**Issue by robstewart57** [marsmining/ox-twbs#14]
When compiling twbs.el to byte code I get the following 2 warnings:

```
In org-twbs-format-latex-arity:
ox-twbs.el:2189:8:Warning: org-format-latex called with 7 arguments, but
    accepts only 1-6

In end of data:
ox-twbs.el:3140:1:Warning: the following functions are not known to be defined:
    org-translate-time, org-publish-resolve-external-fuzzy-link
```

With GNU Emacs 24.5.1 .

**Comment by marsmining** [comment]
Thanks for the feedback!

I can definitely say the arity warning for `org-format-latex` is ok, and occurs because of a change somewhere between org-mode 8.2x to 8.3.x. I'm handling it [like this](https://github.com/marsmining/ox-twbs/blob/cfe67353d148e65a7676f1609d8cc22a4c8fbc78/ox-twbs.el#L2183-L2190), but I'm unsure if this is an idiomatic way of handling this type of problem.

The subsequent warning is something that needs to be looked into.

**Comment by marsmining** [comment]
With the following commits I believe compilation against org-mode 8.2.x and 8.3.x should be warning free.

12e696d7dc9c63e334e6b53e09e398b2a2d407c7
127fca975a8e6dca03945bfcc0478e6b3cf1743e
65bcdee1c640757c9b82eb9c8d588d4851b588f2

Thanks for taking time to report the issue!
