### ISSUE TITLE
Should respect toc option

### ISSUE THREAD

**Issue by mlt** [marsmining/ox-twbs#4]
It seems that ox-twbs places a table of contents regardless of toc option. This results in a duplication of TOC if such option was set. Once right after _container_ & _rows_ divs and then just before the footer. I mean

```
#+OPTIONS: toc:t
```

**Comment by marsmining** [comment]
Thanks for finding this bug. I've never wanted to turn table of contents off. I've pushed a commit to fix this, but the default right now is toc off. That might need changing.

2388109ed20ad739988efdf4da46777252bcd4b6

**Comment by marsmining** [comment]
Changed default so toc is on with depth two.

bc28bb2b51c66b1dc3199dd557c7237006ef6694

**Comment by mlt** [comment]
Thanks! Few more toc related things. What is the purpose for timer to affix it? Though I've changed things around for me and I use panel with heading, it works okay if I unwrap affixation away from timer.
Another thing, that it would probably make sense either to hide toc or pull it left on small devices. toc past document doesn't make sense :-)

**Comment by marsmining** [comment]
There was a timeout initializing the affix plugin but has since been removed. Now it's pretty [straight-forward](https://github.com/marsmining/ox-twbs/blob/0d2ccf66fb0b45d47397cf30ef94a929ad131b8c/ox-twbs.el#L163-L173). Does that answer your question regarding timer?

Thanks for your time and feedback!
